In [1]:
import numpy as np

In [5]:
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
import numpy as np
np.random.seed(2)
matrix= np.random.rand(9,5)
print("Random Matrix:")
print (matrix)

Random Matrix:
[[0.4359949  0.02592623 0.54966248 0.43532239 0.4203678 ]
 [0.33033482 0.20464863 0.61927097 0.29965467 0.26682728]
 [0.62113383 0.52914209 0.13457995 0.51357812 0.18443987]
 [0.78533515 0.85397529 0.49423684 0.84656149 0.07964548]
 [0.50524609 0.0652865  0.42812233 0.09653092 0.12715997]
 [0.59674531 0.226012   0.10694568 0.22030621 0.34982629]
 [0.46778748 0.20174323 0.64040673 0.48306984 0.50523672]
 [0.38689265 0.79363745 0.58000418 0.1622986  0.70075235]
 [0.96455108 0.50000836 0.88952006 0.34161365 0.56714413]]


In [63]:
import numpy as np

matrix=np.arange(45).reshape(9,5)
print (matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]


In [74]:
import numpy as np
matrix = np.arange(9).reshape(3,3)
col_sum =np.sum(matrix[:,1])
col_mean =np.mean(matrix[:,2])
print (matrix)
print(col_sum)
print(col_mean)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
12
5.0


In [8]:
import numpy as np
matrix=np.arange(12).reshape(3,4)
print (matrix)
column_sum = 0
column_count =0
for row in matrix:
    column_sum =column_sum + row[1]
    column_count=column_sum + 1
if column_count>0:
   column_mean = column_sum / column_count
else:
   column_mean = 0
print ("Mean of the 2nd column:",column_mean)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Mean of the 2nd column: 0.9375


In [46]:
import numpy as np
vector =np.array([36,25,16,3,5,6])
sqrt_vector = np.zeros_like(vector)
for i in range(len(vector)):
  sqrt_vector[i] = np.sqrt(vector[i])
print (sqrt_vector)

[6 5 4 1 2 2]


In [52]:
import numpy as np
vector = np.array([35,23,22,11,3,5])
sqrt_vector = np.zeros_like(vector)
for i in range (len(vector)):
   sqrt_vector[i]=np.sqrt(vector[i])
print ("sqrt vector:",sqrt_vector)

sqrt vector: [5 4 4 3 1 2]


In [104]:
import numpy as np
def square_vector(n):
    vector=np.arange (n,0,-1)**2
    return vector

input_num = 6
output_vector = square_vector(input_num)

print ("Output vector:",output_vector)

Output vector: [36 25 16  9  4  1]


In [108]:
import numpy as np
def square_vector(n):
    vector =np.arange(n,0,-1)**2
    return vector
input_num = 10
output_vector = square_vector(input_num)
print (output_vector)

[100  81  64  49  36  25  16   9   4   1]
