In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [9]:
import numpy as np
import time

SIZE = 1000

# Create Python lists
l1 = range(SIZE)
l2 = range(SIZE)

# Measure time for Python list addition
start = time.time()
result = [(x + y) for x, y in zip(l1, l2)]
print("Python list took:", (time.time() - start) * 1000, "ms")

# Create NumPy arrays
a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

# Measure time for NumPy array addition
start = time.time()
result = a1 + a2
print("NumPy array took:", (time.time() - start) * 1000, "ms")




Python list took: 0.0 ms
NumPy array took: 0.0 ms


In [13]:
import numpy as np

In [27]:
a=np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
for row in a:
    for cell in row:
          print(cell)   

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [35]:
for cell in a.flatten():
    print (cell)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [37]:
for x in np.nditer(a,order='F', flags =['external_loop']):
    print(x)

[ 0  5 10 15]
[ 1  6 11 16]
[ 2  7 12 17]
[ 3  8 13 18]
[ 4  9 14 19]


In [39]:
for x in np.nditer (a,order ='F',flags =['external_loop']):
    print(x)

[ 0  5 10 15]
[ 1  6 11 16]
[ 2  7 12 17]
[ 3  8 13 18]
[ 4  9 14 19]


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print (arr)


[1 2 3 4 5 6]


In [14]:
import numpy as np 
arr=np.array ([[1,2,3,4,5],[2,345,56,67,2]])
print (arr)


[[  1   2   3   4   5]
 [  2 345  56  67   2]]


In [18]:
print (type(arr))

<class 'numpy.ndarray'>


In [22]:
zeros=np.zeros ((4,4))
print (zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
ones = np.ones((2,4))
print (ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [34]:
arr= np.arange(0,100,5)
print (arr)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
